### ISSUE TITLE
Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by nickolai** [sequitur/raconteur-scaffold#4]
When trying to compile a project with 'gulp', there's an error:

> [21:37:32] Using gulpfile ~/Dropbox/raconteur-scaffold-master/Gulpfile.js
> [21:37:32] Task 'default' is not in your gulpfile
> [21:37:32] Please check the documentation for proper gulpfile formatting

**Comment by sequitur** [comment]
Fixed in 21c49b17f3f34e75b0fbd7f3a82060074ba3e090
